---
driver:
  name: docker
  use_sudo: false
  privileged: true

provisioner:
  name: chef_zero
  attributes:
    poise-service:
      provider: dummy
    diff-info-service:
      CI: "<%= ENV['CI'] %>"


# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: ubuntu-15.10

suites:
  - name: default
    run_list:
      - recipe[diff-info-service::default]
    attributes:
