name 'diff-info-service'
maintainer 'The Authors'
maintainer_email 'you@example.com'
source_url 'https://github.com/ScottG489/diff-info-service-cookbook'
issues_url 'https://github.com/ScottG489/diff-info-service-cookbook/issues'
license 'all_rights'
description 'Installs/Configures diff-info-service'
long_description 'Installs/Configures diff-info-service'
version '0.1.7'

depends 'apt', '~> 2.9.2'
depends 'docker', '~> 2.0'
depends 'java', '~> 1.39.0'
depends 'poise-service', '~> 1.1.1'
